### ISSUE TITLE
You are breaking SOLID, single responsability

### ISSUE THREAD

**Issue by vCamilx** [RisasDev/BetterStaff#3]
You are breaking the principle, single responsability, for example, in the class [FreezeListener](https://github.com/RisasDev/BetterStaff/blob/main/src/main/java/dev/risas/betterstaff/listeners/FreezeListener.java), you are putting more than 1 listener. In the [StaffListener](https://github.com/RisasDev/BetterStaff/blob/main/src/main/java/dev/risas/betterstaff/listeners/StaffListener.java) likewise, you are breaking this.

You should create a separate class for each listener.

**Comment by Sakiio** [comment]
Thanks later i see to fix it
